language: node_js
dist: bionic
node_js:
  - '10'

addons:

branches:
  only:
    - main

# build the webapp into ./dist
script:
  - bash scripts/build-travis.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $TRAVIS_TOKEN
  target-branch: gh-pages
  on:
    branch: main
