language: node_js
dist: bionic
node_js:
  - '12'

addons:

branches:
  only:
    - source

# build the webapp into ./dist
script:
  - bash scripts/build-travis.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $TRAVIS_TOKEN
  target_branch: master
  on:
    branch: source
