[projects]

[projects.avoev]
  name = 'AVÖV'
  url = 'avoev'
  description = 'AVÖV Project Files (runs-svn)'
  svn = 'https://svn.vsp.tu-berlin.de/repos/runs-svn/avoev/'
  need_password = true

[projects.public-svn]
  name = 'Public SVN'
  url = 'public-svn'
  description = 'Public MATSim scenarios at VSP'
  svn = 'https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/'
  need_password = false

[projects.shared-svn]
  name = 'Shared SVN: Projects'
  url = 'shared-svn'
  description = 'Test shared-svn access with username/pw'
  svn = 'https://svn.vsp.tu-berlin.de/repos/shared-svn/projects/'
  need_password = true

[projects.local]
  name = 'Localhost (Auth)'
  url = 'local'
  description = "Verwenden Sie 'scripts/serve.py', um auf lokale Dateien ohne Server zuzugreifen."
  svn = 'http://localhost/'
  need_password = true

[projects.serve]
  name = 'Serve.py'
  url = 'serve'
  description = 'Local files served by python script serve.py'
  svn = 'http://localhost:8000/'
  need_password = false
